apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - secrets.yaml
  - ingress.yaml

images:
  - name: typing-game-backend
    newName: ACCOUNT_ID.dkr.ecr.REGION.amazonaws.com/typing-game-backend
    newTag: latest

commonLabels:
  app: typing-game-backend
  managed-by: kustomize
