apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- deployment.yaml
- secrets.yaml
- ingress.yaml

images:
- name: typing-game-backend
  newName: 222634400055.dkr.ecr.ap-northeast-2.amazonaws.com/typing-challenge
  newTag: e9a2b7617e8e33134d2cf17379ca5c615ea73945

commonLabels:
  app: typing-game-backend
  managed-by: kustomize
