apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- deployment.yaml
- secrets.yaml
- ingress.yaml

images:
- name: typing-game-backend
  newName: 222634400055.dkr.ecr.ap-northeast-2.amazonaws.com/typing-challenge
  newTag: 2a75b5f4b94955c455a719fdda647d4af34b58cf

commonLabels:
  app: typing-game-backend
  managed-by: kustomize
